# Site
repository: matrixvampire/matrixvampire.github.io
favicon: images/favicon.ico

# Personal info
name: Basanta Raj Onta
title: Software Engineer/IT Specialist
email: basanta.onta@gmail.com
# website: https://matrixvampire.github.io/

# Social links
twitter_username: matrixvampire
github_username:  matrixvampire
# facebook_username: basanta.onta
# instagram_username: basanta.onta
linkedin_username: basantarajonta
#youtube_username: matrixVampire

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Basanta. I am from Nepal, currently residing and working in Thailand. I am a Software Engineer. I am working as IT Specialist/Development Team Lead with Ascend Money. I am helping Ascend Money with their Equator Platform, payment and wallet platform for their regioanl countries. Right now, this platform is integreted with TrueMoney in Vietnam, Myanmmar, Cambodia, Philipins, and Indonesia. In capacity as Development Team Lead, I lead a team of developers helping them to achieve their personal and business goals. 

  I am most skilled in: <mark>Java</mark> and <mark>Spring</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Hiking
   - Reading
   - Watching new TV series and movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
